// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeriodicTableApi.Repositories;

#nullable disable

namespace PeriodicTableApi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20260518113837_InitialFullPeriodicTable")]
    partial class InitialFullPeriodicTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PeriodicTableApi.Models.Element", b =>
                {
                    b.Property<int>("Number")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AtomNumber");

                    b.Property<string>("Appearance")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AtomicMass")
                        .HasColumnType("REAL");

                    b.Property<string>("Block")
                        .HasColumnType("TEXT");

                    b.Property<string>("BohrModel3D")
                        .HasColumnType("TEXT");

                    b.Property<string>("BohrModelImage")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Boil")
                        .HasColumnType("REAL");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("CpkHex")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Density")
                        .HasColumnType("REAL");

                    b.Property<string>("DiscoveredBy")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ElectronAffinity")
                        .HasColumnType("REAL");

                    b.Property<string>("ElectronConfiguration")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElectronConfigurationSemantic")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ElectronegativityPauling")
                        .HasColumnType("REAL");

                    b.Property<int?>("ElementImageId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Group")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IonizationEnergiesRaw")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Melt")
                        .HasColumnType("REAL");

                    b.Property<double?>("MolarHeat")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamedBy")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Period")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phase")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShellsRaw")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpectralImg")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Wxpos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Wypos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Xpos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Ypos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Number");

                    b.HasIndex("ElementImageId");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("PeriodicTableApi.Models.ElementImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attribution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ElementImages");
                });

            modelBuilder.Entity("PeriodicTableApi.Models.Element", b =>
                {
                    b.HasOne("PeriodicTableApi.Models.ElementImage", "Image")
                        .WithMany()
                        .HasForeignKey("ElementImageId");

                    b.Navigation("Image");
                });
#pragma warning restore 612, 618
        }
    }
}
