// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeriodicTableApi.Repositories;

#nullable disable

namespace PeriodicTableApi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20260518093617_InitialFullPeriodicTable")]
    partial class InitialFullPeriodicTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PeriodicTableApi.Models.Element", b =>
                {
                    b.Property<int>("Number")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AtomNumber");

                    b.Property<string>("Appearance")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AtomicMass")
                        .HasColumnType("REAL");

                    b.Property<string>("Block")
                        .HasColumnType("TEXT");

                    b.Property<string>("BohrModel3D")
                        .HasColumnType("TEXT");

                    b.Property<string>("BohrModelImage")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Boil")
                        .HasColumnType("REAL");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("CpkHex")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Density")
                        .HasColumnType("REAL");

                    b.Property<string>("DiscoveredBy")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ElectronAffinity")
                        .HasColumnType("REAL");

                    b.Property<string>("ElectronConfiguration")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElectronConfigurationSemantic")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ElectronegativityPauling")
                        .HasColumnType("REAL");

                    b.Property<int?>("ElementImageId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Group")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IonizationEnergiesRaw")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Melt")
                        .HasColumnType("REAL");

                    b.Property<double?>("MolarHeat")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamedBy")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Period")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phase")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShellsRaw")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpectralImg")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Wxpos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Wypos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Xpos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Ypos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Number");

                    b.HasIndex("ElementImageId");

                    b.ToTable("Elements");

                    b.HasData(
                        new
                        {
                            Number = 1,
                            Appearance = "colorless gas",
                            AtomicMass = 1.008,
                            Block = "s",
                            BohrModel3D = "https://storage.googleapis.com/search-ar-edu/periodic-table/element_001_hydrogen/element_001_hydrogen.glb",
                            BohrModelImage = "https://storage.googleapis.com/search-ar-edu/periodic-table/element_001_hydrogen/element_001_hydrogen_srp_th.png",
                            Boil = 20.271000000000001,
                            Category = "diatomic nonmetal",
                            CpkHex = "ffffff",
                            Density = 0.089880000000000002,
                            DiscoveredBy = "Henry Cavendish",
                            ElectronAffinity = 72.769000000000005,
                            ElectronConfiguration = "1s1",
                            ElectronConfigurationSemantic = "1s1",
                            ElectronegativityPauling = 2.2000000000000002,
                            ElementImageId = 1,
                            Group = 1,
                            IonizationEnergiesRaw = "1312",
                            Melt = 13.99,
                            MolarHeat = 28.835999999999999,
                            Name = "Hydrogen",
                            NamedBy = "Antoine Lavoisier",
                            Period = 1,
                            Phase = "Gas",
                            ShellsRaw = "1",
                            Source = "https://en.wikipedia.org/wiki/Hydrogen",
                            SpectralImg = "https://en.wikipedia.org/wiki/File:Hydrogen_Spectra.jpg",
                            Summary = "Hydrogen is a chemical element with chemical symbol H and atomic number 1. With an atomic weight of 1.00794 u, hydrogen is the lightest element on the periodic table. Its monatomic form (H) is the most abundant chemical substance in the Universe, constituting roughly 75% of all baryonic mass.",
                            Symbol = "H",
                            Wxpos = 1,
                            Wypos = 1,
                            Xpos = 1,
                            Ypos = 1
                        },
                        new
                        {
                            Number = 2,
                            Appearance = "colorless gas, exhibiting a red-orange glow when placed in a high-voltage electric field",
                            AtomicMass = 4.0026022000000001,
                            Block = "s",
                            BohrModel3D = "https://storage.googleapis.com/search-ar-edu/periodic-table/element_002_helium/element_002_helium.glb",
                            BohrModelImage = "https://storage.googleapis.com/search-ar-edu/periodic-table/element_002_helium/element_002_helium_srp_th.png",
                            Boil = 4.2220000000000004,
                            Category = "noble gas",
                            CpkHex = "d9ffff",
                            Density = 0.17860000000000001,
                            DiscoveredBy = "Pierre Janssen",
                            ElectronAffinity = -48.0,
                            ElectronConfiguration = "1s2",
                            ElectronConfigurationSemantic = "1s2",
                            ElementImageId = 2,
                            Group = 18,
                            IonizationEnergiesRaw = "2372.3,5250.5",
                            Melt = 0.94999999999999996,
                            Name = "Helium",
                            Period = 1,
                            Phase = "Gas",
                            ShellsRaw = "2",
                            Source = "https://en.wikipedia.org/wiki/Helium",
                            SpectralImg = "https://en.wikipedia.org/wiki/File:Helium_spectrum.jpg",
                            Summary = "Helium is a chemical element with symbol He and atomic number 2. It is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas that heads the noble gas group in the periodic table. Its boiling and melting points are the lowest among all the elements.",
                            Symbol = "He",
                            Wxpos = 32,
                            Wypos = 1,
                            Xpos = 18,
                            Ypos = 1
                        },
                        new
                        {
                            Number = 3,
                            Appearance = "silvery-white",
                            AtomicMass = 6.9400000000000004,
                            Block = "s",
                            BohrModel3D = "https://storage.googleapis.com/search-ar-edu/periodic-table/element_003_lithium/element_003_lithium.glb",
                            BohrModelImage = "https://storage.googleapis.com/search-ar-edu/periodic-table/element_003_lithium/element_003_lithium_srp_th.png",
                            Boil = 1603.0,
                            Category = "alkali metal",
                            CpkHex = "cc80ff",
                            Density = 0.53400000000000003,
                            DiscoveredBy = "Johan August Arfwedson",
                            ElectronAffinity = 59.632599999999996,
                            ElectronConfiguration = "1s2 2s1",
                            ElectronConfigurationSemantic = "[He] 2s1",
                            ElectronegativityPauling = 0.97999999999999998,
                            ElementImageId = 3,
                            Group = 1,
                            IonizationEnergiesRaw = "520.2,7298.1,11815",
                            Melt = 453.64999999999998,
                            MolarHeat = 24.859999999999999,
                            Name = "Lithium",
                            Period = 2,
                            Phase = "Solid",
                            ShellsRaw = "2,1",
                            Source = "https://en.wikipedia.org/wiki/Lithium",
                            Summary = "Lithium (from Greek:λίθος lithos, \"stone\") is a chemical element with the symbol Li and atomic number 3. It is a soft, silver-white metal belonging to the alkali metal group of chemical elements. Under standard conditions it is the lightest metal and the least dense solid element.",
                            Symbol = "Li",
                            Wxpos = 1,
                            Wypos = 2,
                            Xpos = 1,
                            Ypos = 2
                        });
                });

            modelBuilder.Entity("PeriodicTableApi.Models.ElementImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attribution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ElementImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attribution = "User:Jurii, CC BY 3.0 <https://creativecommons.org/licenses/by/3.0>, via Wikimedia Commons, source: https://images-of-elements.com/hydrogen.php",
                            Title = "Vial of glowing ultrapure hydrogen, H2. Original size in cm: 1 x 5",
                            Url = "https://upload.wikimedia.org/wikipedia/commons/d/d9/Hydrogenglow.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Attribution = "Jurii, CC BY 3.0 <https://creativecommons.org/licenses/by/3.0>, via Wikimedia Commons, source: https://images-of-elements.com/helium.php",
                            Title = "Vial of glowing ultrapure helium. Original size in cm: 1 x 5",
                            Url = "https://upload.wikimedia.org/wikipedia/commons/0/00/Helium-glow.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Attribution = "Hi-Res Images ofChemical Elements, CC BY 3.0 <https://creativecommons.org/licenses/by/3.0>, via Wikimedia Commons, source: https://images-of-elements.com/lithium.php",
                            Title = "0.5 Grams Lithium under Argon. Original size of the largest piece in cm: 0.3 x 4",
                            Url = "https://upload.wikimedia.org/wikipedia/commons/e/e2/0.5_grams_lithium_under_argon.jpg"
                        });
                });

            modelBuilder.Entity("PeriodicTableApi.Models.Element", b =>
                {
                    b.HasOne("PeriodicTableApi.Models.ElementImage", "Image")
                        .WithMany()
                        .HasForeignKey("ElementImageId");

                    b.Navigation("Image");
                });
#pragma warning restore 612, 618
        }
    }
}
